name: Verify and Release

permissions:
  issues: write
  checks: write
  contents: write
  pull-requests: write

on:
  - push
  - pull_request

env:
  LEFTHOOK: 0

jobs:
  release:
    runs-on: self-hosted
    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: 🔧 Set up Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: 'latest'

      - name: 🔧 Set up Go 1.22.6
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: '1.22.6'

      - name: 📦 Install dependencies
        shell: bash
        run: |
          go get .
          npm install semantic-release semantic-release-export-data @semantic-release/changelog @semantic-release/git @semantic-release/github @semantic-release/exec @semantic-release/commit-analyzer @semantic-release/release-notes-generator conventional-changelog-conventionalcommits

      - name: 🔍 Test with the Go CLI
        shell: bash
        run: |
          go install github.com/ctrf-io/go-ctrf-json-reporter/cmd/go-ctrf-json-reporter@latest
          go test -json ./... | go-ctrf-json-reporter -output ctrf-report.json

      - name: 📝 Publish CTRF Test Summary Results
        if: always()
        shell: bash
        run: npx github-actions-ctrf ctrf-report.json

      - name: 🧮 Get next version number
        id: get-next-version
        shell: bash
        run: npx semantic-release --dry-run
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Release
        if: ${{ steps.get-next-version.outputs.new-release-published == 'true' }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          npx semantic-release && \
          GOPROXY=proxy.golang.org go list -m github.com/meza/curseforge-fingerprint-go@v${{ steps.go.outputs.new-release-version }}
