name: Verify and Release

permissions:
  issues: write
  checks: write
  contents: write
  pull-requests: write

on:
  - push
  - pull_request

env:
  LEFTHOOK: 0

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: meza/action-go-ci@main
        id: go
        name: Set up Go
        with:
          go-version: '1.22.6'
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Release
        if: steps.go.new-release-published == 'true'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npx semantic-release && \
          GOPROXY=proxy.golang.org go list -m github.com/meza/curseforge-fingerprint-go@${{ steps.go.outputs.new-release-version }}
